# comfyui-reyrb custom nodes

from .latent_slerp import NODE_CLASS_MAPPINGS as LATENT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY_MAPPINGS
from .clip_vision_to_text import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY_MAPPINGS

# Merge all mappings
NODE_CLASS_MAPPINGS = {**LATENT_MAPPINGS, **CLIP_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**LATENT_DISPLAY_MAPPINGS, **CLIP_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
